// Generates game_data.h: the bundled arcade embedded as a byte array so the
// launcher is a single self-contained .exe with no external files.
// Run `node web/build-single.js` first; build.sh does that for you.
const fs = require("fs");
const path = require("path");

const source = path.join(__dirname, "..", "..", "dist", "pocket-arcade.html");
const target = path.join(__dirname, "game_data.h");

const bytes = fs.readFileSync(source);
const lines = [];
for (let i = 0; i < bytes.length; i += 16) {
  const chunk = [];
  for (let j = i; j < Math.min(i + 16, bytes.length); j++) {
    chunk.push("0x" + bytes[j].toString(16).padStart(2, "0"));
  }
  lines.push("  " + chunk.join(", ") + ",");
}

fs.writeFileSync(target,
  "/* Generated by embed.js - do not edit. Source: web/index.html */\n" +
  "#ifndef MOBCLASH_GAME_DATA_H\n#define MOBCLASH_GAME_DATA_H\n\n" +
  "static const unsigned char GAME_HTML[] = {\n" + lines.join("\n") + "\n};\n\n" +
  "static const unsigned long GAME_HTML_LEN = " + bytes.length + "UL;\n\n" +
  "#endif\n");

console.log("Embedded " + bytes.length + " bytes -> " + target);
